INSERT INTO `TypeRooms` (`id`, `name`, `bedrooms`, `bathrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `quantity`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(1, 'Ocean View One-Bedroom - Double Room', 1, 2, 3, 40, '1 extra-large double bed', 'Air conditioning,Flat-screen TV,Wake-up service', 'The spacious double room provides air conditioning, soundproof walls, a balcony with sea views as well as a private bathroom featuring a bath. The unit offers 1 bed.', 5, 13, '2024-02-29 22:08:41', '2024-02-29 23:25:18');
INSERT INTO `TypeRooms` (`id`, `name`, `bedrooms`, `bathrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `quantity`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(2, 'Ocean View One-Bedroom - Twin Room', 1, 2, 3, 40, '2 single beds', 'Air conditioning,Outdoor furniture,Wake-up service', 'The spacious twin room offers air conditioning, soundproof walls, a balcony with sea views as well as a private bathroom featuring a bath. The unit offers 2 beds.', 5, 13, '2024-02-29 22:09:02', '2024-02-29 23:25:58');
INSERT INTO `TypeRooms` (`id`, `name`, `bedrooms`, `bathrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `quantity`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(3, 'Ocean View Two-Bedroom Villa', 2, 2, 4, 175, '1 extra-large double bed', 'Air conditioning,Minibar,Safety deposit box', 'The suites are located on top of the cliff and offers great views of the ocean. It has a private splash pool, a mini kitchenette, a dining room, 2 bedrooms and a private garden. Facilities include a sofa, a cable TV and an electric kettle. The bathrooms features a bathtub.', 5, 12, '2024-02-29 22:09:05', '2024-02-29 23:26:22');
INSERT INTO `TypeRooms` (`id`, `name`, `bedrooms`, `bathrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `quantity`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(4, '1 Bedroom Superior Suite', 1, 2, 3, 70, '1 extra-large double bed', 'Minibar,Kitchenette,Microwave', 'This suite comes with a large patio balcony offering panoramic ocean and mountain views. It features a separate living room, floor-to-ceiling windows and an en suite bathroom. Benefits include: Minibar (one time fill on arrival) - welcome fruits.', 5, 15, '2024-02-29 23:05:49', '2024-02-29 23:26:47'),
(5, 'Ocean View Pavilion 2 Bedrooms Upper Floor', 2, 2, 5, 157, '1 extra-large double bed,2 single beds', 'Refrigerator,Kitchenette,Minibar', 'Featuring a private balcony with panoramic views of the resort and the ocean, this villa comes with a balcony, electric kettle and minibar. En suite bathroom facilities and flat-screen TV are provided. Guests enjoy a living area and a spa bath at this unit. Benefits include: Minibar (one time fill on arrival) - welcome fruits.', 5, 14, '2024-02-29 23:05:49', '2024-02-29 23:27:13'),
(6, 'Ocean Front Pool Pavilion 3 Bedrooms Ground Floor', 3, 2, 7, 214, '1 extra-large double bed,1 extra-large double bed,2 single beds', 'Sofa,Refrigerator,TV', 'This villa features a private pool, seating area and dining area. The villa has a private balcony, floor-to-ceiling windows and a patio. Benefits include: Minibar (one time fill on arrival) - welcome fruits.', 5, 14, '2024-02-29 23:05:49', '2024-03-01 14:14:03'),
(7, 'Wooden Bungalow with Garden View', 1, 1, 2, 18, '1 large double bed', 'Air conditioning,Flat-screen TV,Minibar', 'The air-conditioned bungalow features 1 bedroom and 1 bathroom with a shower and a hairdryer. Featuring a terrace with garden views, this bungalow also provides a minibar and a flat-screen TV with cable channels. The unit offers 1 bed.', 5, 1, '2024-03-06 19:14:09', '2024-03-06 19:14:09'),
(8, 'Superior Bungalow Double Room with Terrace - Garden View', 1, 1, 2, 24, '1 extra-large double bed', 'Air conditioning,Electric kettle,Minibar', 'This air-conditioned double room includes a flat-screen TV with cable channels, a private bathroom as well as a balcony with garden views. The unit offers 1 bed', 5, 1, '2024-03-06 19:15:57', '2024-03-06 19:15:57'),
(9, 'Superior Bungalow Twin Room with Terrace - Garden View', 1, 1, 2, 24, '2 single beds', 'Air conditioning,Electric kettle,TV', 'This air-conditioned twin room includes a flat-screen TV with cable channels, a private bathroom as well as a terrace with garden views. The unit offers 2 beds.', 5, 1, '2024-03-06 19:16:54', '2024-03-06 19:16:54'),
(10, 'Bungalow with Patio\r\n', 1, 1, 2, 12, '1 large double bed', 'Electric kettle,Air conditioning', 'The bungalow features air conditioning, an electric kettle and a terrace.', 5, 2, '2024-03-06 19:27:20', '2024-03-06 19:27:20'),
(11, 'Deluxe Family Room', 1, 1, 2, 30, '1 double bed ', 'Electric kettle,Air conditioning', 'The family room features air conditioning, an electric kettle and a terrace. The unit has 1 bed.', 5, 2, '2024-03-06 19:29:41', '2024-03-06 19:29:41'),
(12, 'Bungalow with Patio(20m2)', 1, 1, 2, 20, '1 large double bed', 'Electric kettle,Air conditioning', 'The bungalow features air conditioning, an electric kettle and a terrace.', 5, 2, '2024-03-06 19:31:45', '2024-03-06 19:31:45');