INSERT INTO `typerooms` (`id`, `name`, `bedrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(1, 'Ocean View One-Bedroom - Double Room', 1, 3, 40, '1 extra-large double bed', 'Air conditioning,Flat-screen TV,Wake-up service', 'The spacious double room provides air conditioning, soundproof walls, a balcony with sea views as well as a private bathroom featuring a bath. The unit offers 1 bed.', 13, '2024-02-29 22:08:41', '2024-02-29 23:25:18');
INSERT INTO `typerooms` (`id`, `name`, `bedrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(2, 'Ocean View One-Bedroom - Twin Room', 1, 3, 40, '2 single beds', 'Air conditioning,Outdoor furniture,Wake-up service', 'The spacious twin room offers air conditioning, soundproof walls, a balcony with sea views as well as a private bathroom featuring a bath. The unit offers 2 beds.', 13, '2024-02-29 22:09:02', '2024-02-29 23:25:58');
INSERT INTO `typerooms` (`id`, `name`, `bedrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(3, 'Ocean View Two-Bedroom Villa', 2, 4, 175, '1 extra-large double bed', 'Air conditioning,Minibar,Safety deposit box', 'The suites are located on top of the cliff and offers great views of the ocean. It has a private splash pool, a mini kitchenette, a dining room, 2 bedrooms and a private garden. Facilities include a sofa, a cable TV and an electric kettle. The bathrooms features a bathtub.', 12, '2024-02-29 22:09:05', '2024-02-29 23:26:22');
INSERT INTO `typerooms` (`id`, `name`, `bedrooms`, `persons`, `size`, `bedTypes`, `amenities`, `description`, `typeOfProjectID`, `createdAt`, `updatedAt`) VALUES
(4, '1 Bedroom Superior Suite', 1, 3, 70, '1 extra-large double bed', 'Minibar,Kitchenette,Microwave', 'This suite comes with a large patio balcony offering panoramic ocean and mountain views. It features a separate living room, floor-to-ceiling windows and an en suite bathroom. Benefits include: Minibar (one time fill on arrival) - welcome fruits.', 15, '2024-02-29 23:05:49', '2024-02-29 23:26:47'),
(5, 'Ocean View Pavilion 2 Bedrooms Upper Floor', 2, 5, 157, '1 extra-large double bed,2 single beds', 'Refrigerator,Kitchenette,Minibar', 'Featuring a private balcony with panoramic views of the resort and the ocean, this villa comes with a balcony, electric kettle and minibar. En suite bathroom facilities and flat-screen TV are provided. Guests enjoy a living area and a spa bath at this unit. Benefits include: Minibar (one time fill on arrival) - welcome fruits.', 14, '2024-02-29 23:05:49', '2024-02-29 23:27:13'),
(6, 'Ocean Front Pool Pavilion 3 Bedrooms Ground Floor', 3, 7, 214, '1 extra-large double bed,1 extra-large double bed,2 single beds', 'Sofa,Refrigerator,TV', 'This villa features a private pool, seating area and dining area. The villa has a private balcony, floor-to-ceiling windows and a patio. Benefits include: Minibar (one time fill on arrival) - welcome fruits.', 14, '2024-02-29 23:05:49', '2024-02-29 23:27:34');